In [2]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        select  f.name as facility_name, (m.firstname || m.surname ) AS member, count(b.bookid) as usage_count
from Facilities as f
inner join Bookings as b
on f.facid = b.facid
inner join Members as m
on b.memid = m.memid
where b.memid != 0
group by facility_name, member
order by member asc, b.starttime asc 

        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Pool Table', 'AnnaMackenzie', 70)
('Badminton Court', 'AnnaMackenzie', 30)
('Snooker Table', 'AnnaMackenzie', 7)
('Table Tennis', 'AnnaMackenzie', 16)
('Squash Court', 'AnnaMackenzie', 2)
('Massage Room 1', 'AnnaMackenzie', 1)
('Tennis Court 1', 'AnneBaker', 6)
('Massage Room 2', 'AnneBaker', 2)
('Tennis Court 2', 'AnneBaker', 35)
('Squash Court', 'AnneBaker', 49)
('Pool Table', 'AnneBaker', 12)
('Table Tennis', 'AnneBaker', 1)
('Badminton Court', 'AnneBaker', 10)
('Massage Room 1', 'AnneBaker', 3)
('Massage Room 1', 'BurtonTracy', 31)
('Snooker Table', 'BurtonTracy', 20)
('Tennis Court 2', 'BurtonTracy', 3)
('Tennis Court 1', 'BurtonTracy', 31)
('Pool Table', 'BurtonTracy', 30)
('Squash Court', 'BurtonTracy', 35)
('Table Tennis', 'BurtonTracy', 24)
('Badminton Court', 'BurtonTracy', 2)
('Tennis Court 1', 'CharlesOwen', 17)
('Snooker Table', 'CharlesOwen', 22)
('Badminton Court', 'CharlesOwen', 6)
('Table Tennis', 'CharlesOwen', 24)
('Tennis Court 2', 'CharlesOwen', 41)
('Squash Court', 'CharlesOwen', 7)
('Massage Room 1', 'CharlesOwen', 11)
('Massage Room 2', 'CharlesOwen', 2)
('Pool Table', 'CharlesOwen', 1)
('Massage Room 1', 'DarrenSmith', 28)
('Pool Table', 'DarrenSmith', 28)
('Table Tennis', 'DarrenSmith', 28)
('Snooker Table', 'DarrenSmith', 12)
('Squash Court', 'DarrenSmith', 14)
('Badminton Court', 'DarrenSmith', 132)
('Tennis Court 2', 'DarrenSmith', 19)
('Tennis Court 1', 'DavidFarrell', 6)
('Pool Table', 'DavidFarrell', 25)
('Squash Court', 'DavidFarrell', 1)
('Tennis Court 2', 'DavidFarrell', 1)
('Snooker Table', 'DavidFarrell', 1)
('Tennis Court 2', 'DavidJones', 30)
('Table Tennis', 'DavidJones', 11)
('Pool Table', 'DavidJones', 8)
('Badminton Court', 'DavidJones', 8)
('Snooker Table', 'DavidJones', 2)
('Massage Room 1', 'DavidJones', 19)
('Tennis Court 1', 'DavidJones', 25)
('Squash Court', 'DavidJones', 8)
('Massage Room 2', 'DavidJones', 4)
('Snooker Table', 'DavidPinker', 16)
('Badminton Court', 'DavidPinker', 7)
('Table Tennis', 'DavidPinker', 17)
('Pool Table', 'DavidPinker', 9)
('Squash Court', 'DavidPinker', 3)
('Tennis Court 1', 'DavidPinker', 16)
('Massage Room 1', 'DavidPinker', 3)
('Badminton Court', 'DouglasJones', 2)
('Tennis Court 1', 'DouglasJones', 9)
('Squash Court', 'DouglasJones', 1)
('Pool Table', 'DouglasJones', 2)
('Badminton Court', 'EricaCrumpet', 2)
('Massage Room 1', 'EricaCrumpet', 2)
('Table Tennis', 'EricaCrumpet', 2)
('Tennis Court 1', 'EricaCrumpet', 1)
('Pool Table', 'FlorenceBader', 23)
('Badminton Court', 'FlorenceBader', 9)
('Table Tennis', 'FlorenceBader', 42)
('Snooker Table', 'FlorenceBader', 33)
('Tennis Court 2', 'FlorenceBader', 8)
('Massage Room 2', 'FlorenceBader', 2)
('Squash Court', 'FlorenceBader', 2)
('Tennis Court 1', 'FlorenceBader', 1)
('Tennis Court 1', 'GeraldButters', 57)
('Snooker Table', 'GeraldButters', 34)
('Badminton Court', 'GeraldButters', 20)
('Massage Room 1', 'GeraldButters', 32)
('Tennis Court 2', 'GeraldButters', 3)
('Massage Room 2', 'GeraldButters', 1)
('Squash Court', 'GeraldButters', 9)
('Pool Table', 'GeraldButters', 6)
('Table Tennis', 'GeraldButters', 1)
('Pool Table', 'HenriettaRumney', 3)
('Snooker Table', 'HenriettaRumney', 14)
('Tennis Court 2', 'HenriettaRumney', 1)
('Squash Court', 'HenriettaRumney', 2)
('Pool Table', 'HenryWorthington-Smyth', 33)
('Badminton Court', 'HenryWorthington-Smyth', 4)
('Table Tennis', 'HenryWorthington-Smyth', 3)
('Massage Room 1', 'HenryWorthington-Smyth', 1)
('Pool Table', 'HyacinthTupperware', 8)
('Snooker Table', 'HyacinthTupperware', 5)
('Squash Court', 'HyacinthTupperware', 1)
('Badminton Court', 'HyacinthTupperware', 1)
('Massage Room 1', 'HyacinthTupperware', 1)
('Massage Room 1', 'JackSmith', 27)
('Pool Table', 'JackSmith', 7)
('Tennis Court 1', 'JackSmith', 22)
('Snooker Table', 'JackSmith', 5)
('Badminton Court', 'JackSmith', 12)
('Squash Court', 'JackSmith', 9)
('Table Tennis', 'JackSmith', 5)
('Tennis Court 2', 'JackSmith', 1)
('Massage Room 2', 'JackSmith', 1)
('Snooker Table', 'JaniceJoplette', 68)
('Massage Room 1', 'JaniceJoplette', 12)
('Tennis Court 1', 'JaniceJoplette', 19)
('Pool Table', 'JaniceJoplette', 27)
('Massage Room 2', 'JaniceJoplette', 2)
('Squash Court', 'JaniceJoplette', 14)
('Tennis Court 2', 'JaniceJoplette', 8)
('Table Tennis', 'JaniceJoplette', 9)
('Squash Court', 'JemimaFarrell', 8)
('Table Tennis', 'JemimaFarrell', 12)
('Snooker Table', 'JemimaFarrell', 21)
('Badminton Court', 'JemimaFarrell', 7)
('Massage Room 1', 'JemimaFarrell', 29)
('Tennis Court 2', 'JemimaFarrell', 1)
('Tennis Court 1', 'JemimaFarrell', 1)
('Pool Table', 'JemimaFarrell', 1)
('Snooker Table', 'JoanCoplin', 10)
('Table Tennis', 'JoanCoplin', 21)
('Tennis Court 1', 'JoanCoplin', 7)
('Pool Table', 'JoanCoplin', 11)
('Squash Court', 'JoanCoplin', 1)
('Massage Room 2', 'JoanCoplin', 2)
('Massage Room 1', 'JoanCoplin', 1)
('Tennis Court 1', 'JohnHunt', 4)
('Tennis Court 2', 'JohnHunt', 4)
('Massage Room 1', 'JohnHunt', 3)
('Table Tennis', 'JohnHunt', 1)
('Badminton Court', 'JohnHunt', 2)
('Squash Court', 'JohnHunt', 1)
('Massage Room 2', 'MatthewGenting', 1)
('Table Tennis', 'MatthewGenting', 26)
('Massage Room 1', 'MatthewGenting', 25)
('Pool Table', 'MatthewGenting', 18)
('Snooker Table', 'MatthewGenting', 1)
('Tennis Court 1', 'MatthewGenting', 1)
('Pool Table', 'MillicentPurview', 5)
('Badminton Court', 'MillicentPurview', 2)
('Tennis Court 2', 'MillicentPurview', 1)
('Table Tennis', 'MillicentPurview', 6)
('Snooker Table', 'MillicentPurview', 1)
('Squash Court', 'MillicentPurview', 1)
('Snooker Table', 'NancyDare', 23)
('Badminton Court', 'NancyDare', 10)
('Massage Room 1', 'NancyDare', 19)
('Tennis Court 2', 'NancyDare', 11)
('Massage Room 2', 'NancyDare', 5)
('Tennis Court 1', 'NancyDare', 25)
('Pool Table', 'NancyDare', 19)
('Table Tennis', 'NancyDare', 5)
('Tennis Court 2', 'PonderStibbons', 31)
('Snooker Table', 'PonderStibbons', 20)
('Badminton Court', 'PonderStibbons', 16)
('Massage Room 1', 'PonderStibbons', 19)
('Pool Table', 'PonderStibbons', 12)
('Table Tennis', 'PonderStibbons', 3)
('Tennis Court 1', 'PonderStibbons', 1)
('Squash Court', 'PonderStibbons', 2)
('Snooker Table', 'RamnareshSarwin', 18)
('Tennis Court 2', 'RamnareshSarwin', 11)
('Massage Room 1', 'RamnareshSarwin', 8)
('Badminton Court', 'RamnareshSarwin', 7)
('Pool Table', 'RamnareshSarwin', 13)
('Massage Room 2', 'RamnareshSarwin', 3)
('Tennis Court 1', 'RamnareshSarwin', 5)
('Squash Court', 'RamnareshSarwin', 2)
('Table Tennis', 'RamnareshSarwin', 3)
('Tennis Court 2', 'TimBoothe', 52)
('Squash Court', 'TimBoothe', 12)
('Massage Room 1', 'TimBoothe', 36)
('Snooker Table', 'TimBoothe', 43)
('Badminton Court', 'TimBoothe', 12)
('Pool Table', 'TimBoothe', 25)
('Tennis Court 1', 'TimBoothe', 4)
('Table Tennis', 'TimBoothe', 4)
('Massage Room 1', 'TimRownam', 80)
('Pool Table', 'TimRownam', 241)
('Table Tennis', 'TimRownam', 69)
('Tennis Court 2', 'TimRownam', 6)
('Tennis Court 1', 'TimRownam', 6)
('Massage Room 2', 'TimRownam', 2)
('Badminton Court', 'TimRownam', 4)
('Pool Table', 'TimothyBaker', 85)
('Massage Room 1', 'TimothyBaker', 24)
('Tennis Court 2', 'TimothyBaker', 7)
('Table Tennis', 'TimothyBaker', 24)
('Tennis Court 1', 'TimothyBaker', 14)
('Squash Court', 'TimothyBaker', 5)
('Badminton Court', 'TimothyBaker', 7)
('Tennis Court 1', 'TracySmith', 30)
('Pool Table', 'TracySmith', 61)
('Snooker Table', 'TracySmith', 45)
('Table Tennis', 'TracySmith', 28)
('Massage Room 1', 'TracySmith', 6)
('Badminton Court', 'TracySmith', 32)
('Squash Court', 'TracySmith', 6)
('Tennis Court 2', 'TracySmith', 2)